from __future__ import annotations

from typing import Protocol, Any


class Repository(Protocol):
    def list(self, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    def get(self, key: str) -> dict[str, Any] | None: ...
    def create(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, key: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def soft_delete(self, key: str, actor: str, reason: str = "") -> dict[str, Any]: ...
