# -*- coding: utf-8 -*-
"""Neon authority helpers for the original SPT UI.

This is the compatibility layer that lets old pages keep their UI while moving
formal module/settings/audit persistence to PostgreSQL/Neon as the single source
of truth. Local JSON is only used when DATABASE_URL is not configured.
"""
from __future__ import annotations

import json
from datetime import datetime
from typing import Any


def now_text() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _json_default(value: Any) -> Any:
    try:
        import pandas as pd
        if pd.isna(value):
            return None
    except Exception:
        pass
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return str(value)


def is_neon_enabled() -> bool:
    try:
        from services.db_service import is_postgres_enabled
        return bool(is_postgres_enabled())
    except Exception:
        return False


def ensure_neon_authority_schema() -> None:
    """Create additive generic authority tables in Neon.

    Do not drop or rewrite any business table. These tables replace the old
    local JSON/persistent_modules authority files for module settings, traces,
    diagnostics, and module records that do not have a dedicated business table.
    """
    if not is_neon_enabled():
        return
    from services import db_service as _db

    with _db._v25_pg_connect() as conn:  # type: ignore[attr-defined]
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS spt_module_authority (
                    module_key TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    payload TEXT NOT NULL DEFAULT '{}',
                    updated_at TEXT,
                    updated_by TEXT,
                    PRIMARY KEY (module_key, kind)
                )
                """
            )
            for col, ddl in (
                ("kind", "TEXT DEFAULT 'records'"),
                ("payload", "TEXT DEFAULT '{}'"),
                ("updated_at", "TEXT"),
                ("updated_by", "TEXT"),
                ("deleted_at", "TEXT"),
                ("created_at", "TEXT"),
                ("record_key", "TEXT"),
                ("table_name", "TEXT"),
            ):
                try:
                    cur.execute(f"ALTER TABLE spt_module_authority ADD COLUMN IF NOT EXISTS {col} {ddl}")
                except Exception:
                    pass
            try:
                cur.execute("UPDATE spt_module_authority SET kind=COALESCE(NULLIF(kind,''), NULLIF(table_name,''), 'records') WHERE kind IS NULL OR kind=''")
            except Exception:
                pass
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS spt_module_authority_audit (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_time TEXT,
                    module_key TEXT,
                    action TEXT,
                    username TEXT,
                    result TEXT,
                    message TEXT,
                    detail TEXT
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS spt_system_json_store (
                    name TEXT PRIMARY KEY,
                    payload TEXT NOT NULL DEFAULT '{}',
                    updated_at TEXT
                )
                """
            )
            # Soft-delete / tombstone compatible columns for log-like tables.
            for table in ("system_logs", "auth_login_logs", "security_login_logs", "time_records"):
                for col, ddl in (
                    ("deleted_at", "TEXT"),
                    ("deleted_by", "TEXT"),
                    ("delete_reason", "TEXT"),
                ):
                    try:
                        cur.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {col} {ddl}")
                    except Exception:
                        pass
            cur.execute("CREATE INDEX IF NOT EXISTS idx_spt_module_authority_kind ON spt_module_authority(kind)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_spt_module_authority_audit_module_time ON spt_module_authority_audit(module_key, event_time)")
        conn.commit()


def _dumps(payload: Any) -> str:
    return json.dumps(payload, ensure_ascii=False, default=_json_default)


def _loads(text: Any, default: Any = None) -> Any:
    if text is None or text == "":
        return default
    try:
        return json.loads(str(text))
    except Exception:
        return default


def load_payload(module_key: str, kind: str, default: Any = None) -> Any:
    if not is_neon_enabled():
        return default
    ensure_neon_authority_schema()
    from services.db_service import query_one

    row = query_one(
        "SELECT payload FROM spt_module_authority WHERE module_key=? AND kind=?",
        (str(module_key), str(kind)),
    )
    if not row:
        return default
    return _loads(row.get("payload"), default)


def save_payload(module_key: str, kind: str, payload: Any, user: str = "SYSTEM") -> dict[str, Any]:
    if not is_neon_enabled():
        return {"ok": False, "skipped": True, "reason": "postgres_disabled"}
    ensure_neon_authority_schema()
    from services.db_service import execute

    updated = execute(
        """
        UPDATE spt_module_authority
        SET payload=?, updated_at=?, updated_by=?
        WHERE module_key=? AND kind=? AND (deleted_at IS NULL OR deleted_at='')
        """,
        (_dumps(payload), now_text(), str(user or "SYSTEM"), str(module_key), str(kind)),
    )
    if not updated:
        execute(
            """
            INSERT INTO spt_module_authority(module_key, kind, payload, updated_at, updated_by)
            VALUES (?, ?, ?, ?, ?)
            """,
            (str(module_key), str(kind), _dumps(payload), now_text(), str(user or "SYSTEM")),
        )
    return {"ok": True, "backend": "neon", "module_key": str(module_key), "kind": str(kind)}


def load_system_payload(name: str, default: Any = None) -> Any:
    if not is_neon_enabled():
        return default
    ensure_neon_authority_schema()
    from services.db_service import query_one

    row = query_one("SELECT payload FROM spt_system_json_store WHERE name=?", (str(name),))
    if not row:
        return default
    return _loads(row.get("payload"), default)


def save_system_payload(name: str, payload: Any) -> dict[str, Any]:
    if not is_neon_enabled():
        return {"ok": False, "skipped": True, "reason": "postgres_disabled"}
    ensure_neon_authority_schema()
    from services.db_service import execute

    execute(
        """
        INSERT INTO spt_system_json_store(name, payload, updated_at)
        VALUES (?, ?, ?)
        ON CONFLICT (name) DO UPDATE SET payload=EXCLUDED.payload, updated_at=EXCLUDED.updated_at
        """,
        (str(name), _dumps(payload), now_text()),
    )
    return {"ok": True, "backend": "neon", "name": str(name)}


def append_audit(module_key: str, action: str, username: str = "SYSTEM", result: str = "OK", message: str = "", detail: Any = None) -> None:
    if not is_neon_enabled():
        return
    ensure_neon_authority_schema()
    from services.db_service import execute

    execute(
        """
        INSERT INTO spt_module_authority_audit(event_time, module_key, action, username, result, message, detail)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (now_text(), str(module_key), str(action), str(username or "SYSTEM"), str(result), str(message or ""), _dumps(detail or {})),
    )


def authority_status() -> dict[str, Any]:
    if not is_neon_enabled():
        return {"backend": "local", "postgres_enabled": False}
    ensure_neon_authority_schema()
    from services.db_service import query_df

    df = query_df(
        """
        SELECT module_key, kind, updated_at, updated_by, length(payload) AS payload_bytes
        FROM spt_module_authority
        ORDER BY module_key, kind
        """
    )
    rows = df.to_dict("records") if df is not None and not df.empty else []
    return {"backend": "neon", "postgres_enabled": True, "rows": rows, "count": len(rows)}
