# -*- coding: utf-8 -*-
"""SPT Time Tracking - Unified visual theme service.
V1.57: restore compact sidebar spacing + keep logo/header/input/dropdown compatibility.
"""
from __future__ import annotations

import base64
from pathlib import Path
from typing import Any, Iterable

import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOGO_PATHS = [
    PROJECT_ROOT / "data" / "logo" / "super_plus_logo.png",
    PROJECT_ROOT / "data" / "logo" / "logococo(黑字).png",
    PROJECT_ROOT / "assets" / "super_plus_logo.png",
]


def _find_logo() -> Path | None:
    for p in LOGO_PATHS:
        if p.exists() and p.is_file():
            return p
    return None


def _img_to_base64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("utf-8")


def _logo_html() -> str:
    logo = _find_logo()
    if logo:
        try:
            return f'<img class="spt-logo-img" src="data:image/png;base64,{_img_to_base64(logo)}" />'
        except Exception:
            pass
    return '<div class="spt-logo-fallback">SPT</div>'


def apply_theme() -> None:
    """Apply global SPT visual theme. Safe to call on every page."""
    st.markdown(
        """
<style>
:root {
    --spt-bg-0: #050b16;
    --spt-bg-1: #071827;
    --spt-bg-2: #0b2237;
    --spt-cyan: #22e7ff;
    --spt-cyan-soft: rgba(34,231,255,.28);
    --spt-purple: #3f2f99;
    --spt-text: #f2fbff;
    --spt-muted: #aebdca;
    --spt-input-bg: #edf5fb;
    --spt-input-text: #071827;
}

html, body, [data-testid="stAppViewContainer"] {
    background:
        radial-gradient(circle at 18% 12%, rgba(59,42,110,.40), transparent 32%),
        radial-gradient(circle at 92% 8%, rgba(0,180,255,.20), transparent 28%),
        linear-gradient(135deg, #070a18 0%, #071522 48%, #082336 100%) !important;
    color: var(--spt-text) !important;
}

[data-testid="stAppViewBlockContainer"] {
    padding-top: 2.1rem !important;
    max-width: 1560px !important;
}

/* ===== Sidebar: compact spacing + previous glow style ===== */
[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #071421 0%, #06111f 52%, #071522 100%) !important;
    border-right: 1px solid rgba(34,231,255,.18) !important;
    box-shadow: inset -8px 0 30px rgba(0,210,255,.05) !important;
}
[data-testid="stSidebar"] * {
    font-family: "Microsoft JhengHei", "Noto Sans TC", system-ui, sans-serif !important;
}
[data-testid="stSidebar"] [data-testid="stMarkdownContainer"] p {
    color: #e8f8ff !important;
}

/* Streamlit multipage links */
[data-testid="stSidebar"] [data-testid="stPageLink"] {
    margin: 0.02rem 0 !important;
}
[data-testid="stSidebar"] [data-testid="stPageLink"] a,
[data-testid="stSidebar"] a[data-testid="stSidebarNavLink"] {
    min-height: 2.12rem !important;
    padding: 0.28rem 0.58rem !important;
    margin: 0.03rem 0.08rem !important;
    border-radius: 12px !important;
    font-size: 1.02rem !important;
    font-weight: 800 !important;
    line-height: 1.08 !important;
    letter-spacing: .01em !important;
    color: #f4fbff !important;
    text-shadow: 0 0 8px rgba(220,250,255,.22) !important;
    transition: all .18s ease-in-out !important;
}
[data-testid="stSidebar"] [data-testid="stPageLink"] a:hover,
[data-testid="stSidebar"] a[data-testid="stSidebarNavLink"]:hover {
    background: linear-gradient(90deg, rgba(34,231,255,.22), rgba(88,55,190,.33)) !important;
    box-shadow: 0 0 14px rgba(34,231,255,.22), inset 0 0 0 1px rgba(34,231,255,.26) !important;
    transform: translateX(1px) !important;
}
[data-testid="stSidebar"] [data-testid="stPageLink"] a[aria-current="page"],
[data-testid="stSidebar"] a[data-testid="stSidebarNavLink"][aria-current="page"] {
    background: linear-gradient(90deg, rgba(34,231,255,.44), rgba(83,52,198,.72)) !important;
    color: #ffffff !important;
    box-shadow: 0 0 18px rgba(34,231,255,.42), 0 0 34px rgba(70,60,210,.20), inset 0 0 0 1px rgba(34,231,255,.58) !important;
    animation: sptSidebarPulse 2.4s ease-in-out infinite !important;
}
@keyframes sptSidebarPulse {
    0%,100% { box-shadow: 0 0 12px rgba(34,231,255,.28), inset 0 0 0 1px rgba(34,231,255,.48); }
    50% { box-shadow: 0 0 24px rgba(34,231,255,.62), 0 0 42px rgba(82,64,214,.28), inset 0 0 0 1px rgba(34,231,255,.74); }
}

/* Reduce excessive vertical gaps generated by sidebar nav list */
[data-testid="stSidebar"] nav ul { gap: 0 !important; }
[data-testid="stSidebar"] nav li { margin: 0.02rem 0 !important; padding: 0 !important; }

/* ===== Header cards ===== */
.spt-header-wrap {
    display: flex;
    align-items: center;
    gap: 28px;
    padding: 26px 28px;
    margin: 12px 0 26px 0;
    border: 1px solid rgba(34,231,255,.52);
    border-radius: 22px;
    background: linear-gradient(110deg, rgba(8,24,38,.92), rgba(8,78,103,.68));
    box-shadow: 0 0 26px rgba(34,231,255,.20), inset 0 0 0 1px rgba(255,255,255,.03);
    animation: sptHeaderGlow 3.0s ease-in-out infinite;
}
@keyframes sptHeaderGlow {
    0%,100% { box-shadow: 0 0 18px rgba(34,231,255,.18), inset 0 0 0 1px rgba(255,255,255,.03); }
    50% { box-shadow: 0 0 34px rgba(34,231,255,.34), 0 0 54px rgba(76,52,205,.16), inset 0 0 0 1px rgba(34,231,255,.10); }
}
.spt-logo-box {
    width: 270px;
    min-width: 220px;
    height: 92px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(255,255,255,.96);
    border-radius: 14px;
    box-shadow: 0 10px 24px rgba(0,0,0,.22);
    overflow: hidden;
}
.spt-logo-img { max-width: 245px; max-height: 78px; object-fit: contain; }
.spt-logo-fallback { color:#071827; font-size: 2rem; font-weight: 900; letter-spacing: .18em; }
.spt-header-title {
    font-size: 2.15rem;
    font-weight: 900;
    color: #f5fcff;
    letter-spacing: .02em;
    text-shadow: 0 0 12px rgba(255,255,255,.20), 0 0 22px rgba(34,231,255,.16);
    line-height: 1.18;
}
.spt-header-subtitle {
    margin-top: .55rem;
    color: rgba(226,242,255,.78);
    font-size: 1.02rem;
    font-weight: 650;
}

/* KPI / module cards */
.spt-card-grid { display:grid; grid-template-columns: repeat(4, minmax(180px, 1fr)); gap: 14px; margin: 18px 0 24px 0; }
.spt-card, .spt-module-card {
    border: 1px solid rgba(34,231,255,.22);
    border-radius: 14px;
    padding: 16px 18px;
    background: rgba(8,24,38,.76);
    box-shadow: 0 0 16px rgba(34,231,255,.08);
}
.spt-card-label, .spt-module-desc { color: rgba(230,245,255,.70); font-weight: 700; font-size: .86rem; }
.spt-card-value { color:#fff; font-size:1.65rem; font-weight:900; margin-top:.35rem; }
.spt-module-no { color:#7ef5ff; font-size: .95rem; font-weight: 900; }
.spt-module-name { color:#fff; font-size:1.28rem; font-weight:900; margin:.25rem 0 .45rem 0; }

/* ===== Inputs: light background + dark text ===== */
input, textarea, [data-baseweb="input"] input, [data-baseweb="base-input"] input, [data-baseweb="textarea"] textarea,
.stTextInput input, .stTextArea textarea, .stNumberInput input {
    background: var(--spt-input-bg) !important;
    color: var(--spt-input-text) !important;
    border: 1px solid rgba(80,200,255,.62) !important;
    border-radius: 12px !important;
    font-weight: 800 !important;
    caret-color: #061422 !important;
}
input::placeholder, textarea::placeholder { color: rgba(15,35,55,.58) !important; }

/* Select closed field: light bg + dark text */
[data-baseweb="select"] > div {
    background: var(--spt-input-bg) !important;
    border: 1px solid rgba(80,200,255,.62) !important;
    border-radius: 12px !important;
}
[data-baseweb="select"] > div *, [data-baseweb="select"] input {
    color: var(--spt-input-text) !important;
    font-weight: 800 !important;
}

/* Select dropdown menu: dark bg + light text */
[data-baseweb="popover"], [data-baseweb="menu"], ul[role="listbox"] {
    background: #071522 !important;
    border: 1px solid rgba(34,231,255,.34) !important;
    border-radius: 12px !important;
    box-shadow: 0 12px 28px rgba(0,0,0,.42), 0 0 18px rgba(34,231,255,.12) !important;
}
[data-baseweb="menu"] *, ul[role="listbox"] *, [role="option"] * {
    color: #eefaff !important;
    font-weight: 800 !important;
}
[role="option"]:hover, [aria-selected="true"] {
    background: #2ce7f3 !important;
}
[role="option"]:hover *, [aria-selected="true"] * {
    color: #061422 !important;
    font-weight: 900 !important;
}

/* Data editor active cell input */
[data-testid="stDataEditor"] input,
[data-testid="stDataEditor"] textarea,
[data-testid="stDataEditor"] [data-baseweb="select"] > div {
    background: var(--spt-input-bg) !important;
    color: var(--spt-input-text) !important;
    font-weight: 800 !important;
}

button[kind="secondary"], .stButton button {
    border: 1px solid rgba(34,231,255,.48) !important;
    background: rgba(6,52,75,.75) !important;
    color: #f2fbff !important;
    font-weight: 850 !important;
    border-radius: 12px !important;
}
.stButton button:hover {
    box-shadow: 0 0 16px rgba(34,231,255,.30) !important;
    border-color: rgba(34,231,255,.88) !important;
}
</style>
        """,
        unsafe_allow_html=True,
    )


def app_theme() -> None:
    apply_theme()


def render_header(title: str, subtitle: str = "", module_no: str | None = None, **_: Any) -> None:
    """Unified module header."""
    display_title = f"{module_no}｜{title}" if module_no and not str(title).strip().startswith(str(module_no)) else title
    st.markdown(
        f"""
<div class="spt-header-wrap">
  <div class="spt-logo-box">{_logo_html()}</div>
  <div>
    <div class="spt-header-title">{display_title}</div>
    <div class="spt-header-subtitle">{subtitle or ''}</div>
  </div>
</div>
        """,
        unsafe_allow_html=True,
    )


def render_home_header(*_: Any, **__: Any) -> None:
    render_header(
        "超慧科技製造部｜智慧工時紀錄系統",
        "Super Plus Tech Manufacturing Time Tracking System｜Streamlit + SQLite + GitHub Cloud Storage",
    )


def _normalize_kpi_items(items: Any) -> list[tuple[str, str]]:
    if items is None:
        return []
    normalized: list[tuple[str, str]] = []
    if isinstance(items, dict):
        for k, v in items.items():
            normalized.append((str(k), str(v)))
        return normalized
    try:
        for item in items:
            if isinstance(item, dict):
                label = item.get("label") or item.get("title") or item.get("name") or ""
                value = item.get("value") or item.get("number") or item.get("count") or ""
                normalized.append((str(label), str(value)))
            elif isinstance(item, (list, tuple)) and len(item) >= 2:
                normalized.append((str(item[0]), str(item[1])))
            else:
                normalized.append(("", str(item)))
    except Exception:
        pass
    return normalized


def render_kpi_cards(items: Any = None, *args: Any, **kwargs: Any) -> None:
    """Render KPI cards. Compatible with old tuple/list/dict calls."""
    cards = _normalize_kpi_items(items)
    if not cards and args:
        cards = _normalize_kpi_items(args[0])
    if not cards:
        cards = [("核心模組 / Modules", "12"), ("資料庫 / Database", "SQLite"), ("雲端保存 / Cloud", "GitHub"), ("狀態 / Status", "Online")]
    html = ['<div class="spt-card-grid">']
    for label, value in cards:
        html.append(f'<div class="spt-card"><div class="spt-card-label">{label}</div><div class="spt-card-value">{value}</div></div>')
    html.append("</div>")
    st.markdown("".join(html), unsafe_allow_html=True)


def _normalize_modules(modules: Any = None) -> list[tuple[str, str, str]]:
    default = [
        ("01", "工時紀錄", "快速開始、同步作業、暫停、下班、完工與工時計算"),
        ("02", "歷史紀錄", "完整工時明細查詢、編輯、儲存與 Excel 匯出"),
        ("03", "製令管理", "Excel 匯入、貼上資料、手動新增與製令主檔維護"),
        ("04", "人員名單", "人員主檔、在廠狀態、今日出勤與名單維護"),
        ("05", "製令工時分析", "製令累積工時、工段分析與明細查詢"),
        ("06", "LOG查詢", "系統操作、異常與資料異動紀錄查詢"),
        ("07", "今日未紀錄名單", "出勤但未登錄工時的人員即時提示"),
        ("08", "人員每日工時", "每日累積工時、合理區間與異常提醒"),
        ("09", "資料永久保存與備份", "GitHub 雲端永久保存與還原"),
        ("10", "權限管理", "帳號、角色與模組權限設定"),
        ("11", "登入紀錄", "登入、登出與安全事件查詢"),
        ("12", "模組永久紀錄中心", "各模組獨立永久紀錄檔與設定檔"),
    ]
    if modules is None:
        return default
    out: list[tuple[str, str, str]] = []
    try:
        for i, m in enumerate(modules, start=1):
            if isinstance(m, dict):
                out.append((str(m.get("no") or f"{i:02d}"), str(m.get("name") or m.get("title") or ""), str(m.get("desc") or m.get("description") or "")))
            elif isinstance(m, (list, tuple)):
                no = str(m[0]) if len(m) > 0 else f"{i:02d}"
                name = str(m[1]) if len(m) > 1 else ""
                desc = str(m[2]) if len(m) > 2 else ""
                out.append((no, name, desc))
    except Exception:
        return default
    return out or default


def render_module_cards(modules: Any = None, *args: Any, **kwargs: Any) -> None:
    cards = _normalize_modules(modules)
    html = ['<div class="spt-card-grid">']
    for no, name, desc in cards:
        html.append(
            f'<div class="spt-module-card"><div class="spt-module-no">{no}</div><div class="spt-module-name">{name}</div><div class="spt-module-desc">{desc}</div></div>'
        )
    html.append("</div>")
    st.markdown("".join(html), unsafe_allow_html=True)
