[theme]
base="dark"
primaryColor="#31D7FF"
backgroundColor="#07111F"
secondaryBackgroundColor="#0C1A2E"
textColor="#EEF7FF"
font="sans serif"

[client]
showErrorDetails=true

[browser]
gatherUsageStats=false
